/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nerdle.pkg20011028;

import java.util.Random;
import java.io.File;  
import java.io.IOException;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ana_menu extends javax.swing.JFrame {
    private String[] semboller;
    private String[] denklem;
    private String[] yedili ={"3","1","-","3","0","=","1"};
    private String[] sekizli ={"3","1","+","6","2","=","9","3"};
    private String[] dokuzlu ={"3","1","+","9","3","=","1","2","4"};
    /**
     * Creates new form dokuzlu_oyun
     */
    public ana_menu() {
        this.semboller = new String[]{"+","-","*","/"};
        this.denklem = new String[10];
        initComponents();
    }
    
    public static boolean isNumeric(String string) {
        int intValue;

        if(string == null || string.equals("")) {
            return false;
        }

        try {
            intValue = Integer.parseInt(string);
            return true;
        } catch (NumberFormatException e) { 
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        text_ist_5 = new javax.swing.JTextField();
        text_ist_1 = new javax.swing.JTextField();
        text_ist_2 = new javax.swing.JTextField();
        text_ist_3 = new javax.swing.JTextField();
        text_ist_4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(567, 760));
        setPreferredSize(new java.awt.Dimension(567, 760));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Yeni Oyun");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 180, 86));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("Devam Et");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 180, 90));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setText("Test");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 180, 90));

        jLabel1.setText("20011028-Onur Eray Bölük");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 700, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setText("NERDLE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 200, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 220, 80));

        text_ist_5.setText("\"Başarıyla tamamlanan oyunlar ortalama 0 sürede tamamlanmış.");
        text_ist_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ist_5ActionPerformed(evt);
            }
        });
        getContentPane().add(text_ist_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 440, 30));

        text_ist_1.setText("0 oyun yarıda bırakılmış.");
        text_ist_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ist_1ActionPerformed(evt);
            }
        });
        getContentPane().add(text_ist_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 300, 30));

        text_ist_2.setText("0 oyun başarısızlıkla sonuçlanmış.");
        getContentPane().add(text_ist_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 300, 30));

        text_ist_3.setText("0 oyun başarıyla tamamlanmış.");
        text_ist_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ist_3ActionPerformed(evt);
            }
        });
        getContentPane().add(text_ist_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 300, 30));

        text_ist_4.setText("Başarıyla tamamlanan oyunlar ortalama 0 satırda tamamlanmış.");
        getContentPane().add(text_ist_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 380, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String[] generateEquation(){
        
        int a,b,c,d;
        Random rand = new Random();
        /*for(int i=0;i<100;i++){
            a=rand.nextInt(4,6);
            System.out.println(a);
        }
        */
        a=rand.nextInt(3);

        if(a==0){
            String[] denklem = new String[7];
            a=rand.nextInt(4,6);
            if(a==4){
                denklem[4]="=";
                a=rand.nextInt(1,3);
                if(a==1){
                    a=rand.nextInt(2);
                    if(a==0){
                        denklem[1]="+"; 
                        do{
                            System.out.println("1");
                            b=rand.nextInt(10);
                            c=rand.nextInt(10,100);
                            d=(b+c);
                        }while(!( d/10<10 && d/10>=1));
                        denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                        denklem[2]=String.valueOf(String.valueOf(c).charAt(0));
                        denklem[3]=String.valueOf(String.valueOf(c).charAt(1));
                        denklem[5]=String.valueOf(String.valueOf(d).charAt(0));
                        denklem[6]=String.valueOf(String.valueOf(d).charAt(1));
                    }
                    else if(a==1){
                        denklem[1]="*";
                        do{
                            System.out.println("2");
                            b=rand.nextInt(10);
                            c=rand.nextInt(10,100);
                            d=(b*c);
                        }while(!( d/10<10 && d/10>=1));
                        denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                        denklem[2]=String.valueOf(String.valueOf(c).charAt(0));
                        denklem[3]=String.valueOf(String.valueOf(c).charAt(1));
                        denklem[5]=String.valueOf(String.valueOf(d).charAt(0));
                        denklem[6]=String.valueOf(String.valueOf(d).charAt(1));
                    }
                }
                else if(a==2){
                    a=rand.nextInt(4);
                    if(a==0){
                        denklem[2]="+"; 
                        do{
                            System.out.println("3");
                            b=rand.nextInt(10,100);
                            c=rand.nextInt(10);
                            d=(b+c);
                        }while(!( d/10<10 && d/10>=1));
                        denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                        denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                        denklem[3]=String.valueOf(String.valueOf(c).charAt(0));
                        denklem[5]=String.valueOf(String.valueOf(d).charAt(0));
                        denklem[6]=String.valueOf(String.valueOf(d).charAt(1));
                    }
                    else if(a==1){
                        denklem[2]="-"; 
                        do{
                            System.out.println("4");
                            b=rand.nextInt(10,100);
                            c=rand.nextInt(10);
                            d=(b-c);
                        }while(!( d/10<10 && d/10>=1));
                        denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                        denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                        denklem[3]=String.valueOf(String.valueOf(c).charAt(0));
                        denklem[5]=String.valueOf(String.valueOf(d).charAt(0));
                        denklem[6]=String.valueOf(String.valueOf(d).charAt(1));
                    }
                    else if(a==2){
                        denklem[2]="*"; 
                        do{
                            System.out.println("5");
                            b=rand.nextInt(10,100);
                            c=rand.nextInt(10);
                            d=(b*c);
                        }while(!( d/10<10 && d/10>=1));
                        denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                        denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                        denklem[3]=String.valueOf(String.valueOf(c).charAt(0));
                        denklem[5]=String.valueOf(String.valueOf(d).charAt(0));
                        denklem[6]=String.valueOf(String.valueOf(d).charAt(1));
                    }
                    else if(a==3){
                        denklem[2]="/"; 
                        do{
                            System.out.println("6");
                            d=rand.nextInt(10,100);
                            c=rand.nextInt(10);
                            b=(d*c);
                        }while(!( b/10<10 && b/10>=1));
                        denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                        denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                        denklem[3]=String.valueOf(String.valueOf(c).charAt(0));
                        denklem[5]=String.valueOf(String.valueOf(d).charAt(0));
                        denklem[6]=String.valueOf(String.valueOf(d).charAt(1));
                    }
                }
            }
            else if(a==5){
                denklem[5]="=";
                a=rand.nextInt(2);
                if(a==0){
                        
                    denklem[2]="-"; 
                        do{
                            System.out.println("8");
                            b=rand.nextInt(10,100);
                            c=rand.nextInt(10,100);
                            d=(b-c);
                        }while(!( d<10 && d>=1));
                        denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                        denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                        denklem[3]=String.valueOf(String.valueOf(c).charAt(0));
                        denklem[4]=String.valueOf(String.valueOf(c).charAt(1));
                        denklem[6]=String.valueOf(String.valueOf(d).charAt(0));
                    }
                    else if(a==1){
                        denklem[2]="/"; 
                        do{
                            System.out.println("10");
                            d=rand.nextInt(10);
                            c=rand.nextInt(10,100);
                            b=(d*c);
                        }while(!( b/10<10 && b/10>=1));
                        denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                        denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                        denklem[3]=String.valueOf(String.valueOf(c).charAt(0));
                        denklem[4]=String.valueOf(String.valueOf(c).charAt(1));
                        denklem[6]=String.valueOf(String.valueOf(d).charAt(0));
                    }
                
            }
            return denklem;
            
        }
        else if(a==1){
            String[] denklem = new String[8];
            a=rand.nextInt(4,7);
            if(a==4){
                denklem[4]="=";
                a=rand.nextInt(1,3);
                if(a==1){
                    a=rand.nextInt(2);
                    if(a==0){
                            denklem[1]="+"; 
                            do{
                                b=rand.nextInt(10);
                                c=rand.nextInt(10,100);
                                d=(b+c);
                            }while(!( d/100<10 && d/100>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[2]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[3]=String.valueOf(String.valueOf(c).charAt(1));
                            denklem[5]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[6]=String.valueOf(String.valueOf(d).charAt(1));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(2));
                    }
                    else if(a==1){
                        denklem[1]="*"; 
                            do{
                                b=rand.nextInt(10);
                                c=rand.nextInt(10,100);
                                d=(b*c);
                            }while(!( d/100<10 && d/100>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[2]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[3]=String.valueOf(String.valueOf(c).charAt(1));
                            denklem[5]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[6]=String.valueOf(String.valueOf(d).charAt(1));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(2));
                    }
                }
                else if(a==2){
                    a=rand.nextInt(2);
                    if(a==0){
                        denklem[2]="+"; 
                            do{
                                b=rand.nextInt(10,100);
                                c=rand.nextInt(10);
                                d=(b+c);
                            }while(!( d/100<10 && d/100>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[3]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[5]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[6]=String.valueOf(String.valueOf(d).charAt(1));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(2));
                    }
                    else if(a==1){
                        denklem[2]="*"; 
                            do{
                                b=rand.nextInt(10,100);
                                c=rand.nextInt(10);
                                d=(b*c);
                            }while(!( d/100<10 && d/100>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[3]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[5]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[6]=String.valueOf(String.valueOf(d).charAt(1));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(2));
                    }
                }
            }
            else if(a==5){
                denklem[5]="=";
                a=rand.nextInt(2,4);
                if(a==2){
                    a=rand.nextInt(2);
                    if(a==0){
                        denklem[2]="+"; 
                            do{
                                b=rand.nextInt(10,100);
                                c=rand.nextInt(10,100);
                                d=(b+c);
                            }while(!( d/10<10 && d/10>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[3]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(1));
                            denklem[6]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(1));
                    }
                    else if(a==1){
                        denklem[2]="-"; 
                            do{
                                b=rand.nextInt(10,100);
                                c=rand.nextInt(10,100);
                                d=(b-c);
                            }while(!( d/10<10 && d/10>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[3]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(1));
                            denklem[6]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(1));
                    }
                }
                else if(a==3){
                    a=rand.nextInt(2);
                    if(a==0){
                        denklem[3]="-"; 
                            do{
                                b=rand.nextInt(100,1000);
                                c=rand.nextInt(10);
                                d=(b-c);
                            }while(!( d/10<10 && d/10>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[2]=String.valueOf(String.valueOf(b).charAt(2));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[6]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(1));
                    }
                    else if(a==1){
                        denklem[3]="/"; 
                            do{
                                d=rand.nextInt(10,100);
                                c=rand.nextInt(10);
                                b=(d*c);
                            }while(!( b/100<10 && b/100>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[2]=String.valueOf(String.valueOf(b).charAt(2));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[6]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(1));
                    }
                }
            }
            else if(a==6){
                denklem[6]="=";
                a=rand.nextInt(2);
                if(a==0){
                    denklem[3]="-"; 
                            do{
                                b=rand.nextInt(100,1000);
                                c=rand.nextInt(10,100);
                                d=(b-c);
                            }while(!( d<10 && d>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[2]=String.valueOf(String.valueOf(b).charAt(2));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[5]=String.valueOf(String.valueOf(c).charAt(1));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(0));
                }
                else if(a==1){
                    denklem[3]="/"; 
                            do{
                                d=rand.nextInt(10);
                                c=rand.nextInt(10,100);
                                b=(d*c);
                            }while(!( b/100<10 && b/100>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[2]=String.valueOf(String.valueOf(b).charAt(2));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[5]=String.valueOf(String.valueOf(c).charAt(1));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(0));
                }
            }
            return denklem;
            
        }
        
        else if(a==2){
            String[] denklem = new String[9];
            a=rand.nextInt(5,8);
            if(a==5){
                denklem[5]="=";
                a=rand.nextInt(1,4);
                if(a==1){
                    a=rand.nextInt(2);
                    if(a==0){
                        denklem[1]="+";
                            do{
                                b=rand.nextInt(10);
                                c=rand.nextInt(100,1000);
                                d=(b+c);
                            }while(!( d/100<10 && d/100>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[2]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[3]=String.valueOf(String.valueOf(c).charAt(1));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(2));
                            denklem[6]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(1));
                            denklem[8]=String.valueOf(String.valueOf(d).charAt(2));
                    }
                    else if(a==1){
                        denklem[1]="*";
                            do{
                                b=rand.nextInt(10);
                                c=rand.nextInt(100,1000);
                                d=(b*c);
                            }while(!( d/100<10 && d/100>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[2]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[3]=String.valueOf(String.valueOf(c).charAt(1));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(2));
                            denklem[6]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(1));
                            denklem[8]=String.valueOf(String.valueOf(d).charAt(2));
                    }
                }
                else if(a==2){
                    a=rand.nextInt(2);
                    if(a==0){
                        denklem[2]="+";
                        do{
                                b=rand.nextInt(10,100);
                                c=rand.nextInt(10,100);
                                d=(b+c);
                            }while(!( d/100<10 && d/100>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[3]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(1));
                            denklem[6]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(1));
                            denklem[8]=String.valueOf(String.valueOf(d).charAt(2));
                    }
                    else if(a==1){
                        denklem[2]="*";
                        do{
                                b=rand.nextInt(10,100);
                                c=rand.nextInt(10,100);
                                d=(b*c);
                            }while(!( d/100<10 && d/100>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[3]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(1));
                            denklem[6]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(1));
                            denklem[8]=String.valueOf(String.valueOf(d).charAt(2));
                    }
                }
                else if(a==3){
                    a=rand.nextInt(4);
                    if(a==0){
                        denklem[3]="+";
                        do{
                                b=rand.nextInt(100,1000);
                                c=rand.nextInt(10);
                                d=(b+c);
                            }while(!( d/100<10 && d/100>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[2]=String.valueOf(String.valueOf(b).charAt(2));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[6]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(1));
                            denklem[8]=String.valueOf(String.valueOf(d).charAt(2));
                    }
                    else if(a==1){
                        denklem[3]="-";
                        do{
                                b=rand.nextInt(100,1000);
                                c=rand.nextInt(10);
                                d=(b-c);
                            }while(!( d/100<10 && d/100>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[2]=String.valueOf(String.valueOf(b).charAt(2));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[6]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(1));
                            denklem[8]=String.valueOf(String.valueOf(d).charAt(2));
                    }
                    else if(a==2){
                        denklem[3]="*";
                        do{
                                b=rand.nextInt(100,1000);
                                c=rand.nextInt(10);
                                d=(b*c);
                            }while(!( d/100<10 && d/100>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[2]=String.valueOf(String.valueOf(b).charAt(2));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[6]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(1));
                            denklem[8]=String.valueOf(String.valueOf(d).charAt(2));
                    }
                    else if(a==3){
                        denklem[3]="/";
                        do{
                                d=rand.nextInt(100,1000);
                                c=rand.nextInt(10);
                                b=(d*c);
                            }while(!( b/100<10 && b/100>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[2]=String.valueOf(String.valueOf(b).charAt(2));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[6]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(1));
                            denklem[8]=String.valueOf(String.valueOf(d).charAt(2));
                    }
                }
            }
            else if(a==6){
                denklem[6]="=";
                a=rand.nextInt(2);
                if(a==0){
                    denklem[3]="-";
                    do{
                                b=rand.nextInt(100,1000);
                                c=rand.nextInt(10,100);
                                d=(b-c);
                            }while(!( d/10<10 && d/10>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[2]=String.valueOf(String.valueOf(b).charAt(2));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[5]=String.valueOf(String.valueOf(c).charAt(1));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[8]=String.valueOf(String.valueOf(d).charAt(1));
                }
                else if(a==1){
                    denklem[3]="/";
                    do{
                                d=rand.nextInt(10,100);
                                c=rand.nextInt(10,100);
                                b=(d*c);
                            }while(!( b/100<10 && b/100>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[2]=String.valueOf(String.valueOf(b).charAt(2));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[5]=String.valueOf(String.valueOf(c).charAt(1));
                            denklem[7]=String.valueOf(String.valueOf(d).charAt(0));
                            denklem[8]=String.valueOf(String.valueOf(d).charAt(1));
                }
            }
            else if(a==7){
                denklem[7]="=";
                a=rand.nextInt(2);
                if(a==0){
                    denklem[3]="-";
                    do{
                                b=rand.nextInt(100,1000);
                                c=rand.nextInt(100,1000);
                                d=(b-c);
                            }while(!( d<10 && d>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[2]=String.valueOf(String.valueOf(b).charAt(2));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[5]=String.valueOf(String.valueOf(c).charAt(1));
                            denklem[6]=String.valueOf(String.valueOf(c).charAt(2));
                            denklem[8]=String.valueOf(String.valueOf(d).charAt(0));
                }
                else if(a==1){
                    denklem[3]="/";
                    do{
                                d=rand.nextInt(10);
                                c=rand.nextInt(100,1000);
                                b=(d*c);
                            }while(!( b/100<10 && b/100>=1));
                            denklem[0]=String.valueOf(String.valueOf(b).charAt(0));
                            denklem[1]=String.valueOf(String.valueOf(b).charAt(1));
                            denklem[2]=String.valueOf(String.valueOf(b).charAt(2));
                            denklem[4]=String.valueOf(String.valueOf(c).charAt(0));
                            denklem[5]=String.valueOf(String.valueOf(c).charAt(1));
                            denklem[6]=String.valueOf(String.valueOf(c).charAt(2));
                            denklem[8]=String.valueOf(String.valueOf(d).charAt(0));
                }
            }
            return denklem;
        }
        
        /*int a,b,c,d;
        
        try{
            Random rand = new Random();
  
            if(rand.nextInt(3) == 0){
                a=rand.nextInt(2);
                if(a==1){
                    denklem[1]=semboller[rand.nextInt(3)];
                    denklem[3]=semboller[rand.nextInt(3)];
                    denklem[5]="=";
                    if("+".equals(denklem[1])){
                        do(){
                        
                        }while((a+b)/10>1);
                        
                    }
                    denklem[3]=semboller[rand.nextInt(3)];
                }
                else{
                    
                }
            }
            else if(rand.nextInt(3) == 1){
                
            }
            else{
                
            }

            return denklem;
        }
        catch(ArithmeticException e){
              
            
            
            
        }     
       */ 
        return denklem;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String[] denklem1;
        denklem1=generateEquation();
        if(denklem1.length==7){
            yedili_oyun g = new yedili_oyun(denklem1);
            g.setVisible(true);
            this.dispose();
        }
        else if(denklem1.length==8){
            sekizli_oyun g = new sekizli_oyun(denklem1);
            g.setVisible(true);
            this.dispose();
        }
        else if(denklem1.length==9){
            dokuzlu_oyun g = new dokuzlu_oyun(denklem1);
            g.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i=0;
        try {
            File myObj = new File("DevamEt.txt");
            Scanner myReader = new Scanner(myObj);
            String time = myReader.nextLine();
            
            if(isNumeric(time)==true){
                
                String denklem = myReader.nextLine();
                String denklem1[];

                if(denklem.length()==7){
                    denklem1 = new String [8];
                    for(i=0;i<7;i++)
                        denklem1[i]=String.valueOf(denklem.charAt(i));
                    myReader.close();
                    yedili_oyun b = new yedili_oyun(denklem1,Integer.valueOf(time));
                    b.setVisible(true);
                    this.dispose();
                }
                else if(denklem.length()==8){
                    denklem1 = new String [9];
                    for(i=0;i<8;i++)
                        denklem1[i]=String.valueOf(denklem.charAt(i));
                    myReader.close();
                    sekizli_oyun b = new sekizli_oyun(denklem1,Integer.valueOf(time));
                    b.setVisible(true);
                    this.dispose();
                }
                else if(denklem.length()==9){
                    denklem1 = new String [10];
                    for(i=0;i<9;i++)
                        denklem1[i]=String.valueOf(denklem.charAt(i));
                    myReader.close();
                    dokuzlu_oyun b = new dokuzlu_oyun(denklem1,Integer.valueOf(time));
                    b.setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Devam Et dosyasında sorun var yeni oyun olusturuluyor...");
                    generateEquation();
                }
            }    
            else{
                JOptionPane.showMessageDialog(null,"Devam Et dosyasında sorun var yeni oyun olusturuluyor...");
                generateEquation();
            }    
            
            myReader.close();
        } 
        catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null,"Kaydedilen oyun bulunamıyor, yeni oyun açın!!");
          }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        StringBuffer sb = new StringBuffer();
        String[] denklem = new String[10];
        denklem=generateEquation();
        for(int i = 0; i < denklem.length; i++) {
            sb.append(denklem[i]);
        }
        String str = sb.toString();
        JOptionPane.showMessageDialog(null,str);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void text_ist_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ist_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_ist_1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int i=1;
        try {
            File myObj = new File("istatislik.txt");
            Scanner myReader = new Scanner(myObj);
            String a;
            if(myReader.hasNextLine()==false){
                    FileWriter fwrite = new FileWriter("istatislik.txt");
                    PrintWriter printWriter = new PrintWriter(fwrite);
                    myObj.delete();
                    myObj.createNewFile();
                    printWriter.print("0\n");
                    printWriter.print("0\n");
                    printWriter.print("0\n");
                    printWriter.print("0\n");
                    printWriter.print("0\n");
                    fwrite.close();
            }
            while(myReader.hasNextLine()){
                a=myReader.nextLine();
                if(isNumeric(a)==true){
                    switch(i){
                        case 1: text_ist_1.setText(a+ " oyun yarıda bırakılmış."); break;
                        case 2: text_ist_2.setText(a+ " oyun başarısızlıkla sonuçlanmış."); break;
                        case 3: text_ist_3.setText(a+ " oyun başarıyla tamamlanmış."); break;
                        case 4: text_ist_4.setText("Başarıyla tamamlanan oyunlar ortalama "+a+ " satırda tamamlanmış."); break;
                        case 5: text_ist_5.setText("Başarıyla tamamlanan oyunlar ortalama "+a+ " sürede tamamlanmış."); break;
                    }
                }    
                else{
                    JOptionPane.showMessageDialog(null,"İstatislik dosyasında sorun var yeniden olusturuluyor...");
                    FileWriter fwrite = new FileWriter("istatislik.txt");
                    PrintWriter printWriter = new PrintWriter(fwrite);
                    myObj.delete();
                    myObj.createNewFile();
                    printWriter.print("0\n");
                    printWriter.print("0\n");
                    printWriter.print("0\n");
                    printWriter.print("0\n");
                    printWriter.print("0\n");
                    fwrite.close();
                }
                i++;
            }
            myReader.close();
        } 
        catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null,"Istatislik dosyayı bulunamıyor!! Yeniden olusturuldu");
            File myObj = new File("istatislik.txt");
            try {
                FileWriter fwrite = new FileWriter("istatislik.txt");
                PrintWriter printWriter = new PrintWriter(fwrite);
                    myObj.delete();
                    myObj.createNewFile();
                    printWriter.print("0\n");
                    printWriter.print("0\n");
                    printWriter.print("0\n");
                    printWriter.print("0\n");
                    printWriter.print("0\n");
                    fwrite.close();
            } catch (IOException ex) {
                
            }     
        } 
        catch (IOException ex) {
            Logger.getLogger(ana_menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void text_ist_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ist_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_ist_5ActionPerformed

    private void text_ist_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ist_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_ist_3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ana_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ana_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ana_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ana_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ana_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField text_ist_1;
    private javax.swing.JTextField text_ist_2;
    private javax.swing.JTextField text_ist_3;
    private javax.swing.JTextField text_ist_4;
    private javax.swing.JTextField text_ist_5;
    // End of variables declaration//GEN-END:variables
}
